on:
  push:
    branches:
      - 'develop'
      - 'release/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: TestActionDev
        if: github.ref == 'refs/heads/develop'
        run: echo 'pushed to develop'
      - name: TestActionAcc
        if: contains('refs/heads/release/', github.ref)
        run: echo ${GITHUB_REF}
